{{- define "ejlevin1.clusterroles" -}}
{{ $root := $ }}
{{- range .Values.clusterRoles }}
  {{- include "ejlevin1.clusterrole" (dict "Root" $root "clusterRoleRoot" .) }}
{{- end }}
{{- end }}

{{- define "ejlevin1.clusterrole" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ required "A .name is is required on ClusterRole." .clusterRoleRoot.name }}
  {{- include "ejlevin1.helm-labels" . | nindent 2 }}
  {{- include "ejlevin1.annotations" . | indent 2 }}
rules:
    {{- with .clusterRoleRoot.rules }}
        {{- toYaml . | nindent 2 }}
    {{- end }}
---
{{- if or .clusterRoleRoot.serviceAccounts .clusterRoleRoot.groups }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .clusterRoleRoot.name }}-binding
  {{- include "ejlevin1.helm-labels" . | nindent 2 }}
  {{- include "ejlevin1.annotations" . | indent 2 }}
roleRef:
  kind: ClusterRole
  name: {{ .clusterRoleRoot.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  {{- include "ejlevin1.clusterrole-serviceaccount-binding" . | indent 2 }}
  {{- include "ejlevin1.clusterrole-groups-binding" . | nindent 2 }}
  {{- include "ejlevin1.clusterrole-users-binding" . | nindent 2 }}
---
{{- end }}
{{- end }}

{{- define "ejlevin1.clusterrole-serviceaccount-binding" -}}
{{ $root := .Root }}
{{- if .clusterRoleRoot.serviceAccounts }}
{{- range .clusterRoleRoot.serviceAccounts }}
- kind: ServiceAccount
  name: {{ required "A serviceAccount.name must be specified to bind to a role." .name }}
  namespace: {{ default $root.Release.Namespace .namespace }}
{{- end }}
{{- end }}
{{- end }}

{{- define "ejlevin1.clusterrole-groups-binding" -}}
{{- if .clusterRoleRoot.groups }}
{{- range .clusterRoleRoot.groups }}
- kind: Group
  name: {{ required "A group.name must be specified to bind to a role." .name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}


{{- define "ejlevin1.clusterrole-users-binding" -}}
{{- if .clusterRoleRoot.users }}
{{- range .clusterRoleRoot.users }}
- kind: User
  name: {{ required "A user.name must be specified to bind to a role." .name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}