{{- define "ejlevin1.service-accounts" }}
{{ $root := $ }}
{{- if .Values.serviceAccounts }}
  {{- range .Values.serviceAccounts }}
    {{- include "ejlevin1.service-account" (dict "root" $root "serviceAccountRoot" .) }}
  {{- end }}
{{- else }}
# No Service Account defined (flagged by .Values.serviceaccount.create)
{{- end }}
{{- end }}

{{- define "ejlevin1.service-account" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".name is required on service object" .serviceAccountRoot.name }}
  namespace: {{ .root.Release.Namespace }}
  {{- include "ejlevin1.generic.labels" (dict "root" .root "Values" .serviceAccountRoot) | nindent 2 }}
  {{- include "ejlevin1.generic.annotations" (dict "root" .root "Values" .serviceAccountRoot) | nindent 2 }}
---
{{- end }}

{{- define "ejlevin1.serviceaccount" }}
{{- if (.Values.serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "A serviceaccount name is required." .Values.serviceAccount.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}